### ISSUE TITLE
about nrings 

### ISSUE THREAD

**Issue by okimoto1** [yogeshverma1998/Modular-Flows-Neurips-2022#1]
For training,

python testing_JT.py/testing_JT_3D.py --esamples #number_of_samples_to_generate --data #dataset --nrings #number_of_rings  --model_name #name/location_of_model_in_Models_folder

--nrings #number_of_rings 
I don't know the value of nrings. 
I would appreciate it if you could tell me what this value is.

**Comment by yogeshverma1998** [comment]
The code that you have mentioned in the post is the code for testing not the training of the model. 

We considered the 20 most common appearing ring structures to train the JT model, but one has a choice to modify its value decided by --nrings that you want to consider. Note that it must be the same during training and testing time.
